services:
  api:
    build: ./api
    expose: 
      - '3000'
    ports:
      - "3002:3000"
    
  carts:
    build: ./carts
    expose: 
      - '3000'

  orders:
    build: ./orders
    expose: 
      - '3000'
  
  products:
    build: ./products
    expose: 
      - '3000'

  users:
    build: ./users
    expose: 
      - '3000'

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"

  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: parduotuve
      MYSQL_ROOT_PASSWORD: labaislaptasraktas
      MYSQL_USER: vartotojas
      MYSQL_PASSWORD: vartotojas
    expose: 
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3001:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:
    driver: local